let books = [
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: "The Last Brother",
        author: "Nathacha Appanah",
        desc: "In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family. When a brutal beating lands Raj in the hospital of the prison camp where his father is a guard, he meets a mysterious boy his own age. David is a refugee, one of a group of Jewish exiles whose harrowing journey took them from Nazi occupied Europe to Palestine, where they were refused entry and sent on to indefinite detainment in Mauritius.",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    

]

export default books;