let books = [
    {
        id: 1,
        title: " The Last Brother",
        author: " Nathacha Appanah",
        desc: " In The Last Brother by Nathacha Appanah, 1944 is coming to a close and nine-year-old Raj is unaware of the war devastating the rest of the world. He lives in Mauritius, a remote island in the Indian Ocean, where survival is a daily struggle for his family...",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/review",
        img: "https://drive.google.com/file/d/1gAOzBdQByQTjy4SC2Lgjmp7erZbIPTyp/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: " The Prisoner of Paradise",
        author: " Romesh Gunesekera",
        desc: " When Lucy arrives in Mauritius she is unprepared for the disquieting attractions of Don Lambodar, a young translator from Ceylon. Under the surface there is growing unease, it is 1825...",
        buy_link: "https://www.amazon.com/Prisoner-Paradise-Romesh-Gunesekera/dp/1408804263",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1rlyPTDyXnEW55kKB8R8qB3AHJV0WFxpv/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: " The Prospector",
        author: " J.M.G. Le Clézio",
        desc: "The Prospector is the crowning achievement from one of France's preeminent contemporary novelists and a work rich with sensuality and haunting resonance...",
        buy_link: "https://www.amazon.com/gp/product/1567923801/ref=x_gr_w_bb_sout?ie=UTF8&tag=x_gr_w_bb_sout-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1567923801&SubscriptionId=1MGPYB6YW3HWK55XCGG2",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1LN0o9TDiQnprOYO6j1g9eO4zalj4FhCX/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: " Eve out of Her Ruins",
        author: " Ananda Devi",
        desc: " With brutal honesty and poetic urgency, Ananda Devi relates the tale of four young Mauritians trapped in their country's endless cycle of fear and violence...",
        buy_link: "https://www.amazon.com/gp/product/1555975755/ref=x_gr_w_bb_sout?ie=UTF8",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1_JfmcAOn1tRkbz75u35nrt8w9Kq-zkaE/view?usp=sharing",
        category: "Local",
        price: 500,
    },
    {
        id: 1,
        title: " Silent Winds, Dry Seas",
        author: " Vinod Busjeet",
        desc: " Vinod Busjeet's sweeping debut novel explores the intimate struggle for independence of a young Hindu boy in Mauritius, a small island under British colonial rule in the Indian Ocean...",
        buy_link: "https://www.amazon.com/gp/product/0385547021/ref=x_gr_w_bb_sout?ie=UTF8&tag=x_gr_w_bb_sout-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0385547021&SubscriptionId=1MGPYB6YW3HWK55XCGG2",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/17n2pOsQ1rN7H_NnR8cw8P8Whs0zxgjKT/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: " Kaya Days",
        author: " Nathacha Appanah",
        desc: " In 1999 the Mauritian seggae musician Joseph Réginald Topize, better known as Kaya, was arrested for smoking weed while performing at a concert...",
        buy_link: "https://www.amazon.com/Kaya-Days-Carl-Souza/dp/1949641198/ref=sr_1_1?keywords=9781949641196&linkCode=qs&qid=1653588149&s=books&sr=1-1",
        review_link: "/review",
        img: "https://drive.google.com/file/d/1MxPjMyeLWyv8OH5x-G9wNIwc7A_aVs6R/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    {
        id: 1,
        title: " Golden Bats & Pink Pigeons",
        author: " Gerald Durrell",
        desc: " On this speck of volcanic soil in the middle of a vast sea, a complete, unique and peaceful world was created slowly and carefully...",
        buy_link: "https://www.amazon.com/gp/product/0671507575/ref=x_gr_w_bb_sout?ie=UTF8&tag=x_gr_w_bb_sout-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0671507575&SubscriptionId=1MGPYB6YW3HWK55XCGG2",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1HGjmrKCjq7c56MHlY9YF-0wtR5WyYGzw/view?usp=sharing",
        category: "Local",
        price: 500,
    },
    {
        id: 1,
        title: " The Interrogation",
        author: " J.M.G. Le Clézio",
        desc: " What is The Interrogation? Most likely a myth without distinct delineations. A very solitary young man, Adam Pollo, perhaps the first man, perhaps the last, has a very remarkable interior adventure...",
        buy_link: "https://www.amazon.com/gp/product/1439149410/ref=x_gr_w_bb_sout?ie=UTF8&tag=x_gr_w_bb_sout-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1439149410&SubscriptionId=1MGPYB6YW3HWK55XCGG2",
        review_link: "/reviews",
        img: "https://drive.google.com/file/d/1vf1E5PLtNo8MvEvFjQWGTr0-luPC6lI5/view?usp=sharing",
        category: "Local",
        price: 700,
    },
    

]

export default books;